#!/usr/bin/env bash
# Rebuild the vendored dependency bundles for the docs-organization skill.
#
# lola strips any directory named node_modules from an install, so the two npm
# packages the skill shells out to would never reach an installed copy. They are
# bundled here into vendor/, which lola ships verbatim.
#
# Regenerate with `task vendor` after any dependency bump. CI reruns this and
# fails on a non-empty `git diff vendor/`, so a committed bundle can never drift
# from the version package.json pins.
set -euo pipefail
trap 'echo "build-vendor: FAIL at line $LINENO" >&2' ERR

SCRIPTS_DIR="module/skills/docs-organization/scripts"
VENDOR_DIR="$SCRIPTS_DIR/vendor"

[ -d "$SCRIPTS_DIR/node_modules" ] || {
  echo "build-vendor: $SCRIPTS_DIR/node_modules is missing." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

mkdir -p "$VENDOR_DIR"
ENTRY_DIR="$(mktemp -d "$SCRIPTS_DIR/.vendor-entry.XXXXXX")"
trap 'rm -rf "$ENTRY_DIR"' EXIT

# esbuild resolves bare specifiers from the entry file's directory, so the
# entry points must live inside the scripts tree, not in /tmp.
printf "export * from '@aj-archipelago/merval';\n" > "$ENTRY_DIR/merval.mjs"
printf "export { default } from 'markdown-it';\n"  > "$ENTRY_DIR/markdown-it.mjs"

# The pinned esbuild lives in the scripts tree, not at the repo root this script
# runs from, so invoke it by path rather than letting npx resolve (and fetch) it.
ESBUILD="$SCRIPTS_DIR/node_modules/.bin/esbuild"
[ -x "$ESBUILD" ] || {
  echo "build-vendor: $ESBUILD is missing or not executable." >&2
  echo "             Run 'task vendor', which installs the toolchain first." >&2
  exit 2
}

for name in merval markdown-it; do
  "$ESBUILD" \
    --bundle --format=esm --platform=node \
    --outfile="$VENDOR_DIR/$name.mjs" \
    "$ENTRY_DIR/$name.mjs"
done

# esbuild only preserves /*! */ legal comments, and neither package uses them,
# so attribution is assembled here from the installed package metadata.
{
  echo "# Vendored dependency licenses"
  echo
  echo "Generated by \`task vendor\`. Do not edit by hand."
  echo
  echo "\`merval.mjs\` and \`markdown-it.mjs\` are esbuild bundles of the"
  echo "packages below, all MIT-licensed. Sources and exact versions are"
  echo "pinned in \`../package.json\`."
  echo
  for pkg in @aj-archipelago/merval markdown-it argparse entities linkify-it mdurl punycode.js uc.micro; do
    dir="$SCRIPTS_DIR/node_modules/$pkg"
    [ -d "$dir" ] || continue
    ver="$(node -p "require('./$dir/package.json').version")"
    lic="$(node -p "require('./$dir/package.json').license || 'see LICENSE file'")"
    echo "## $pkg $ver"
    echo
    echo "License: $lic"
    echo
    for f in LICENSE LICENSE.md LICENSE.txt LICENCE; do
      if [ -f "$dir/$f" ]; then
        echo '```text'
        cat "$dir/$f"
        echo '```'
        echo
        break
      fi
    done
  done
} > "$VENDOR_DIR/LICENSES.md"

echo "build-vendor: wrote $VENDOR_DIR/{merval,markdown-it}.mjs and LICENSES.md"
